apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UjEyMzRy
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=


  # myrootpassword: UjEyMzRy
  # mypassword: Q2xhcnVzd2F5XzE=