apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: enesern02/resultserver
        name: resultserver
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: servers-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
          # value: Clarusway_1
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "750Mi"
            cpu: "750m"